packages:
  - packages/*

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vitest: 4.1.11

allowBuilds:
  vite-plus: true

# The Vite Plus core alias uses the Vite Plus version rather than Vite's version.
peerDependencyRules:
  allowedVersions:
    vite: '0.3.0'
